import Image from "next/image";
import { notFound } from "next/navigation";
import { MovieActions } from "@/components/movie-actions";
import { MovieGrid } from "@/components/movie-grid";
import { SectionHeading } from "@/components/ui";
import { WhereToWatch } from "@/components/where-to-watch";
import { backdropUrl, getMovie, getMovies, getProviders, posterUrl } from "@/lib/tmdb";
import { getCurrentUser } from "@/lib/auth";
const collections = { latest: ["now_playing", "Latest releases"], upcoming: ["upcoming", "Upcoming movies"], "top-rated": ["top_rated", "Top rated movies"], popular: ["popular", "Popular movies"] } as const;
export default async function MoviePage({ params }: PageProps<"/movies/[id]">) { const { id } = await params; const collection = collections[id as keyof typeof collections]; if (collection) { const data = await getMovies(collection[0]); return <div className="mx-auto max-w-7xl px-4 py-12"><SectionHeading title={collection[1]}/><MovieGrid movies={data.results}/></div>; } if (!/^\d+$/.test(id)) notFound(); let movie; try { movie = await getMovie(id); } catch { notFound(); } const [providers, user] = await Promise.all([getProviders(id).catch(() => null), getCurrentUser()]); const backdrop = backdropUrl(movie.backdrop_path), poster = posterUrl(movie.poster_path), trailer = movie.videos.results.find((v) => v.site === "YouTube" && v.type === "Trailer"); return <><section className="relative overflow-hidden border-b border-zinc-800">{backdrop && <Image src={backdrop} alt="" fill sizes="100vw" className="object-cover opacity-25"/>}<div className="relative mx-auto grid max-w-7xl gap-8 px-4 py-12 md:grid-cols-[220px_1fr]"><div className="relative aspect-[2/3] overflow-hidden rounded-xl bg-zinc-800">{poster && <Image src={poster} alt={movie.title} fill sizes="220px" className="object-cover"/>}</div><div className="self-end"><p className="text-amber-400">{movie.release_date?.slice(0,4)} · {movie.runtime ?? "—"} min</p><h1 className="mt-2 text-4xl font-black sm:text-6xl">{movie.title}</h1><p className="mt-3 text-zinc-400">{movie.genres.map((g) => g.name).join(" · ")}</p><p className="mt-6 max-w-3xl leading-7 text-zinc-300">{movie.overview}</p><p className="mt-5 text-amber-400">★ {movie.vote_average.toFixed(1)} TMDB</p><div className="mt-5"><MovieActions movieId={id} signedIn={Boolean(user)} inWatchlist={false}/></div></div></div></section><div className="mx-auto grid max-w-7xl gap-12 px-4 py-12 lg:grid-cols-[1fr_360px]"><div className="space-y-12">{trailer && <section><SectionHeading title="Trailer"/><div className="aspect-video overflow-hidden rounded-xl border"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${trailer.key}`} title="Trailer" allowFullScreen/></div></section>}<section><SectionHeading title="Cast"/><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5">{movie.credits.cast.slice(0,10).map((p) => <div key={p.id}><p className="font-medium">{p.name}</p><p className="text-sm text-zinc-500">{p.character}</p></div>)}</div></section><section><SectionHeading title="Similar movies"/><MovieGrid movies={movie.similar.results.slice(0,6)}/></section></div><aside><SectionHeading title="Where to watch"/><WhereToWatch data={providers?.results.IN}/></aside></div></>; }
