"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function MovieActions({ movieId, signedIn, inWatchlist, rating }: { movieId: string; signedIn: boolean; inWatchlist: boolean; rating?: number }) {
  void signedIn;
  const router = useRouter(); const [saved, setSaved] = useState(inWatchlist); const [value, setValue] = useState(rating?.toString() ?? ""); const [message, setMessage] = useState("");
  async function call(url: string, method: string, body?: object) { const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); if (res.status === 401) { router.push("/login"); return false; } if (!res.ok) { setMessage("Something went wrong. Try again."); return false; } return true; }
  async function watchlist() { if (await call(`/api/watchlist/${movieId}`, saved ? "DELETE" : "POST")) { setSaved(!saved); setMessage(saved ? "Removed from watchlist" : "Added to watchlist"); } }
  async function submitRating() { const number = Number(value); if (!Number.isInteger(number) || number < 1 || number > 10) return setMessage("Choose a whole number from 1 to 10."); if (await call(`/api/movies/${movieId}/rating`, "PUT", { value: number })) { setMessage("Your rating is saved."); router.refresh(); } }
  return <div className="flex flex-wrap items-center gap-3"><button onClick={watchlist} className={`rounded-full border px-4 py-2 text-sm font-semibold ${saved ? "border-red-500/60 bg-red-500/10 text-red-300" : "border-zinc-600 bg-zinc-900 text-zinc-100 hover:border-zinc-400"}`}>{saved ? "♥ In watchlist" : "♡ Add to watchlist"}</button><div className="flex overflow-hidden rounded-full border border-zinc-700 bg-zinc-900"><select value={value} onChange={(e) => setValue(e.target.value)} aria-label="Your rating" className="bg-transparent px-3 py-2 text-sm outline-none"><option value="">Rate it</option>{Array.from({ length: 10 }, (_, i) => <option key={i} value={i + 1}>{i + 1} / 10</option>)}</select><button onClick={submitRating} className="border-l border-zinc-700 px-3 text-sm font-semibold text-amber-400">Save</button></div>{message && <span className="w-full text-xs text-zinc-400">{message}</span>}</div>;
}
